#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SVT-HEVC
Version  : 1.4.1
Release  : 3
URL      : https://github.com/OpenVisualCloud/SVT-HEVC/archive/v1.4.1/svt-hevc-1.4.1.tar.gz
Source0  : https://github.com/OpenVisualCloud/SVT-HEVC/archive/v1.4.1/svt-hevc-1.4.1.tar.gz
Summary  : SVT (Scalable Video Technology) for HEVC encoder library
Group    : Development/Tools
License  : GPL-2.0
Requires: SVT-HEVC-bin = %{version}-%{release}
Requires: SVT-HEVC-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : pkg-config
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-base-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : yasm

%description
# Scalable Video Technology for HEVC Encoder (SVT-HEVC Encoder)
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/openvisualcloud/SVT-HEVC?branch=master&svg=true)](https://ci.appveyor.com/project/openvisualcloud/SVT-HEVC)
[![Travis Build Status](https://travis-ci.com/OpenVisualCloud/SVT-HEVC.svg?branch=master)](https://travis-ci.com/OpenVisualCloud/SVT-HEVC)
[![Coverage Status](https://coveralls.io/repos/github/openvisualcloud/SVT-HEVC/badge.svg?branch=master)](https://coveralls.io/github/openvisualcloud/SVT-HEVC?branch=master)

%package bin
Summary: bin components for the SVT-HEVC package.
Group: Binaries

%description bin
bin components for the SVT-HEVC package.


%package dev
Summary: dev components for the SVT-HEVC package.
Group: Development
Requires: SVT-HEVC-lib = %{version}-%{release}
Requires: SVT-HEVC-bin = %{version}-%{release}
Provides: SVT-HEVC-devel = %{version}-%{release}
Requires: SVT-HEVC = %{version}-%{release}

%description dev
dev components for the SVT-HEVC package.


%package lib
Summary: lib components for the SVT-HEVC package.
Group: Libraries

%description lib
lib components for the SVT-HEVC package.


%prep
%setup -q -n SVT-HEVC-1.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570758114
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export CFLAGS="$CFLAGS -march=skylake-avx512 -m64 "
export CXXFLAGS="$CXXFLAGS -march=skylake-avx512 -m64 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1570758114
rm -rf %{buildroot}
pushd clr-build-avx512
%make_install_avx512  || :
popd
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/SvtHevcEncApp
/usr/bin/haswell/SvtHevcEncApp
/usr/bin/haswell/avx512_1/SvtHevcEncApp

%files dev
%defattr(-,root,root,-)
/usr/include/svt-hevc/EbApi.h
/usr/include/svt-hevc/EbApiVersion.h
/usr/include/svt-hevc/EbErrorCodes.h
/usr/lib64/haswell/avx512_1/libSvtHevcEnc.so
/usr/lib64/haswell/libSvtHevcEnc.so
/usr/lib64/libSvtHevcEnc.so
/usr/lib64/pkgconfig/SvtHevcEnc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/libSvtHevcEnc.so.1
/usr/lib64/haswell/libSvtHevcEnc.so.1
/usr/lib64/libSvtHevcEnc.so.1
